apiVersion: v1
kind: Service
metadata:
  name: quiz-ui-service
spec:
  ports:
    - name: http
      targetPort: 3000 # This is the port exposed by the container
      port: 3000 # This is the port exposed by the service
  selector:
    app: quiz-ui